controller_manager:
  ros__parameters:
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    jackal_velocity_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ['front_left_wheel', 'rear_left_wheel']
      right_wheel_names: ['front_right_wheel', 'rear_right_wheel']
      publish_rate: 50

      wheel_separation_multiplier: 1.5
      wheel_radius_multiplier: 1.0

      cmd_vel_timeout: 0.25
      publish_cmd: true
      enable_odom_tf: false

      pose_covariance_diagonal: [0.001, 0.001, 1e6, 1e6, 1e6, 0.03]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 1e6, 1e6, 0.03]

      linear:
        x:
          has_velocity_limits: true
          max_velocity: 2.0
          has_acceleration_limits: true
          max_acceleration: 20.0

      angular:
        z:
          has_velocity_limits: true
          max_velocity: 4.0
          has_acceleration_limits: true
          max_acceleration: 25.0
